### ISSUE TITLE
the package didn't work

### ISSUE THREAD

**Issue by ainuo5213** [jackytck/ali-oss-extra#54]
error happened when I use
Module not found: Error: Can't resolve 'fs' in 'C:\Users\ainuo5213\Desktop\doc-multipage\client\node_modules\_is-there@4.4.4@is-there\lib'

**Comment by jackytck** [comment]
What's your environment and node version?
Check:
```js
var fs = require("fs");
```

**Comment by ainuo5213** [comment]
yeah, it does work when use `window.require()`。
